### ISSUE TITLE
Unable to add new jobs within treeherder

### ISSUE THREAD

**Issue by armenzg** [mozilla/pulse_actions#47]
From @parkouss (https://github.com/mozilla/mozilla_ci_tools/issues/422)
So, I'm not sure if it is the right place for reporting this, and maybe it is a duplicate - feel free to close it if this is the case;

So I pushed to try https://treeherder.mozilla.org/#/jobs?repo=try&revision=da728cb1294e. Now I missed something in the try syntax, so I want to trigger new jobs, that is some talos jobs for the Linux64 and Win32/64 jobs. I used the interface for that, and went to a final 'trigger request sent' message. But nothing appears; Also @jmaher tried without success.

**Comment by armenzg** [comment]
Jan 19 03:34:00 pulse-actions app/worker2.1: INFO:	 New jobs requested by j.parkouss@gmail.com on repo_name try with resultset_id: 85920 
Jan 19 03:34:00 pulse-actions app/worker2.1: root	 INFO:	 New jobs requested by j.parkouss@gmail.com on repo_name try with resultset_id: 85920 
Jan 19 03:34:04 pulse-actions app/worker2.1: Traceback (most recent call last): 
Jan 19 03:34:04 pulse-actions app/worker2.1:   File "pulse_actions/worker.py", line 75, in run_pulse 
Jan 19 03:34:04 pulse-actions app/worker2.1:     pulse.listen() 
Jan 19 03:34:04 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/mozillapulse/consumers.py", line 151, in listen 
Jan 19 03:34:04 pulse-actions app/worker2.1:     self._drain_events_loop() 
Jan 19 03:34:04 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/mozillapulse/consumers.py", line 198, in _drain_events_loop 
Jan 19 03:34:04 pulse-actions app/worker2.1:     self.connection.drain_events(timeout=self.timeout) 
Jan 19 03:34:04 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/kombu/connection.py", line 275, in drain_events 
Jan 19 03:34:04 pulse-actions app/worker2.1:     return self.transport.drain_events(self.connection, **kwargs) 
Jan 19 03:34:04 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 95, in drain_events 
Jan 19 03:34:04 pulse-actions app/worker2.1:     return connection.drain_events(**kwargs) 
Jan 19 03:34:04 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/amqp/connection.py", line 325, in drain_events 
Jan 19 03:34:04 pulse-actions app/worker2.1:     return amqp_method(channel, args, content) 
Jan 19 03:34:04 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/amqp/channel.py", line 1909, in _basic_deliver 
Jan 19 03:34:04 pulse-actions app/worker2.1:     fun(msg) 
Jan 19 03:34:04 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/kombu/messaging.py", line 596, in _receive_callback 
Jan 19 03:34:04 pulse-actions app/worker2.1:     return on_m(message) if on_m else self.receive(decoded, message) 
Jan 19 03:34:04 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/kombu/messaging.py", line 563, in receive 
Jan 19 03:34:04 pulse-actions app/worker2.1:     [callback(body, message) for callback in callbacks] 
Jan 19 03:34:04 pulse-actions app/worker2.1:   File "pulse_actions/worker.py", line 66, in handler_with_dry_run 
Jan 19 03:34:04 pulse-actions app/worker2.1:     return event_handler(data, message, dry_run) 
Jan 19 03:34:04 pulse-actions app/worker2.1:   File "/app/pulse_actions/handlers/route_functions.py", line 15, in route 
Jan 19 03:34:04 pulse-actions app/worker2.1:     treeherder_runnable.on_runnable_job_prod_event(data, message, dry_run) 
Jan 19 03:34:04 pulse-actions app/worker2.1:   File "/app/pulse_actions/handlers/treeherder_runnable.py", line 20, in on_runnable_job_prod_event 
Jan 19 03:34:04 pulse-actions app/worker2.1:     return on_runnable_job_event(data, message, dry_run, stage=False) 
Jan 19 03:34:04 pulse-actions app/worker2.1:   File "/app/pulse_actions/handlers/treeherder_runnable.py", line 65, in on_runnable_job_event 
Jan 19 03:34:04 pulse-actions app/worker2.1:     requester) 
Jan 19 03:34:04 pulse-actions app/worker2.1: Exception: Requester j.parkouss@gmail.com is not allowed to trigger jobs. 
Jan 19 03:54:43 pulse-actions app/worker2.1: INFO:	 New jobs requested by j.parkouss@gmail.com on repo_name try with resultset_id: 85920 
Jan 19 03:54:43 pulse-actions app/worker2.1: root	 INFO:	 New jobs requested by j.parkouss@gmail.com on repo_name try with resultset_id: 85920 
Jan 19 03:54:44 pulse-actions app/worker2.1: Traceback (most recent call last): 
Jan 19 03:54:44 pulse-actions app/worker2.1:   File "pulse_actions/worker.py", line 75, in run_pulse 
Jan 19 03:54:44 pulse-actions app/worker2.1:     pulse.listen() 
Jan 19 03:54:44 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/mozillapulse/consumers.py", line 151, in listen 
Jan 19 03:54:44 pulse-actions app/worker2.1:     self._drain_events_loop() 
Jan 19 03:54:44 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/mozillapulse/consumers.py", line 198, in _drain_events_loop 
Jan 19 03:54:44 pulse-actions app/worker2.1:     self.connection.drain_events(timeout=self.timeout) 
Jan 19 03:54:44 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/kombu/connection.py", line 275, in drain_events 
Jan 19 03:54:44 pulse-actions app/worker2.1:     return self.transport.drain_events(self.connection, **kwargs) 
Jan 19 03:54:44 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 95, in drain_events 
Jan 19 03:54:44 pulse-actions app/worker2.1:     return connection.drain_events(**kwargs) 
Jan 19 03:54:44 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/amqp/connection.py", line 325, in drain_events 
Jan 19 03:54:44 pulse-actions app/worker2.1:     return amqp_method(channel, args, content) 
Jan 19 03:54:44 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/amqp/channel.py", line 1909, in _basic_deliver 
Jan 19 03:54:44 pulse-actions app/worker2.1:     fun(msg) 
Jan 19 03:54:44 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/kombu/messaging.py", line 596, in _receive_callback 
Jan 19 03:54:44 pulse-actions app/worker2.1:     return on_m(message) if on_m else self.receive(decoded, message) 
Jan 19 03:54:44 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/kombu/messaging.py", line 563, in receive 
Jan 19 03:54:44 pulse-actions app/worker2.1:     [callback(body, message) for callback in callbacks] 
Jan 19 03:54:44 pulse-actions app/worker2.1:   File "pulse_actions/worker.py", line 66, in handler_with_dry_run 
Jan 19 03:54:44 pulse-actions app/worker2.1:     return event_handler(data, message, dry_run) 
Jan 19 03:54:44 pulse-actions app/worker2.1:   File "/app/pulse_actions/handlers/route_functions.py", line 15, in route 
Jan 19 03:54:44 pulse-actions app/worker2.1:     treeherder_runnable.on_runnable_job_prod_event(data, message, dry_run) 
Jan 19 03:54:44 pulse-actions app/worker2.1:   File "/app/pulse_actions/handlers/treeherder_runnable.py", line 20, in on_runnable_job_prod_event 
Jan 19 03:54:44 pulse-actions app/worker2.1:     return on_runnable_job_event(data, message, dry_run, stage=False) 
Jan 19 03:54:44 pulse-actions app/worker2.1:   File "/app/pulse_actions/handlers/treeherder_runnable.py", line 65, in on_runnable_job_event 
Jan 19 03:54:44 pulse-actions app/worker2.1:     requester) 
Jan 19 03:54:44 pulse-actions app/worker2.1: Exception: Requester j.parkouss@gmail.com is not allowed to trigger jobs. 
Jan 19 04:33:41 pulse-actions app/worker2.1: INFO:	 New jobs requested by jmaher@mozilla.com on repo_name try with resultset_id: 85920 
Jan 19 04:33:41 pulse-actions app/worker2.1: root	 INFO:	 New jobs requested by jmaher@mozilla.com on repo_name try with resultset_id: 85920 
Jan 19 04:33:43 pulse-actions app/worker2.1: Traceback (most recent call last): 
Jan 19 04:33:43 pulse-actions app/worker2.1:   File "pulse_actions/worker.py", line 75, in run_pulse 
Jan 19 04:33:43 pulse-actions app/worker2.1:     pulse.listen() 
Jan 19 04:33:43 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/mozillapulse/consumers.py", line 151, in listen 
Jan 19 04:33:43 pulse-actions app/worker2.1:     self._drain_events_loop() 
Jan 19 04:33:43 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/mozillapulse/consumers.py", line 198, in _drain_events_loop 
Jan 19 04:33:43 pulse-actions app/worker2.1:     self.connection.drain_events(timeout=self.timeout) 
Jan 19 04:33:43 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/kombu/connection.py", line 275, in drain_events 
Jan 19 04:33:43 pulse-actions app/worker2.1:     return self.transport.drain_events(self.connection, **kwargs) 
Jan 19 04:33:43 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 95, in drain_events 
Jan 19 04:33:43 pulse-actions app/worker2.1:     return connection.drain_events(**kwargs) 
Jan 19 04:33:43 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/amqp/connection.py", line 325, in drain_events 
Jan 19 04:33:43 pulse-actions app/worker2.1:     return amqp_method(channel, args, content) 
Jan 19 04:33:43 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/amqp/channel.py", line 1909, in _basic_deliver 
Jan 19 04:33:43 pulse-actions app/worker2.1:     fun(msg) 
Jan 19 04:33:43 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/kombu/messaging.py", line 596, in _receive_callback 
Jan 19 04:33:43 pulse-actions app/worker2.1:     return on_m(message) if on_m else self.receive(decoded, message) 
Jan 19 04:33:43 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/kombu/messaging.py", line 563, in receive 
Jan 19 04:33:43 pulse-actions app/worker2.1:     [callback(body, message) for callback in callbacks] 
Jan 19 04:33:43 pulse-actions app/worker2.1:   File "pulse_actions/worker.py", line 66, in handler_with_dry_run 
Jan 19 04:33:43 pulse-actions app/worker2.1:     return event_handler(data, message, dry_run) 
Jan 19 04:33:43 pulse-actions app/worker2.1:   File "/app/pulse_actions/handlers/route_functions.py", line 15, in route 
Jan 19 04:33:43 pulse-actions app/worker2.1:     treeherder_runnable.on_runnable_job_prod_event(data, message, dry_run) 
Jan 19 04:33:43 pulse-actions app/worker2.1:   File "/app/pulse_actions/handlers/treeherder_runnable.py", line 20, in on_runnable_job_prod_event 
Jan 19 04:33:43 pulse-actions app/worker2.1:     return on_runnable_job_event(data, message, dry_run, stage=False) 
Jan 19 04:33:43 pulse-actions app/worker2.1:   File "/app/pulse_actions/handlers/treeherder_runnable.py", line 65, in on_runnable_job_event 
Jan 19 04:33:43 pulse-actions app/worker2.1:     requester) 
Jan 19 04:33:43 pulse-actions app/worker2.1: Exception: Requester jmaher@mozilla.com is not allowed to trigger jobs. 
Jan 19 07:13:21 pulse-actions app/worker2.1: root	 INFO:	 New jobs requested by apoirot@mozilla.com on repo_name try with resultset_id: 85937 
Jan 19 07:13:21 pulse-actions app/worker2.1: INFO:	 New jobs requested by apoirot@mozilla.com on repo_name try with resultset_id: 85937 
Jan 19 07:13:22 pulse-actions app/worker2.1: Traceback (most recent call last): 
Jan 19 07:13:22 pulse-actions app/worker2.1:   File "pulse_actions/worker.py", line 75, in run_pulse 
Jan 19 07:13:22 pulse-actions app/worker2.1:     pulse.listen() 
Jan 19 07:13:22 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/mozillapulse/consumers.py", line 151, in listen 
Jan 19 07:13:22 pulse-actions app/worker2.1:     self._drain_events_loop() 
Jan 19 07:13:22 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/mozillapulse/consumers.py", line 198, in _drain_events_loop 
Jan 19 07:13:22 pulse-actions app/worker2.1:     self.connection.drain_events(timeout=self.timeout) 
Jan 19 07:13:22 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/kombu/connection.py", line 275, in drain_events 
Jan 19 07:13:22 pulse-actions app/worker2.1:     return self.transport.drain_events(self.connection, **kwargs) 
Jan 19 07:13:22 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 95, in drain_events 
Jan 19 07:13:22 pulse-actions app/worker2.1:     return connection.drain_events(**kwargs) 
Jan 19 07:13:22 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/amqp/connection.py", line 325, in drain_events 
Jan 19 07:13:22 pulse-actions app/worker2.1:     return amqp_method(channel, args, content) 
Jan 19 07:13:22 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/amqp/channel.py", line 1909, in _basic_deliver 
Jan 19 07:13:22 pulse-actions app/worker2.1:     fun(msg) 
Jan 19 07:13:22 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/kombu/messaging.py", line 596, in _receive_callback 
Jan 19 07:13:22 pulse-actions app/worker2.1:     return on_m(message) if on_m else self.receive(decoded, message) 
Jan 19 07:13:22 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/kombu/messaging.py", line 563, in receive 
Jan 19 07:13:22 pulse-actions app/worker2.1:     [callback(body, message) for callback in callbacks] 
Jan 19 07:13:22 pulse-actions app/worker2.1:   File "pulse_actions/worker.py", line 66, in handler_with_dry_run 
Jan 19 07:13:22 pulse-actions app/worker2.1:     return event_handler(data, message, dry_run) 
Jan 19 07:13:22 pulse-actions app/worker2.1:   File "/app/pulse_actions/handlers/route_functions.py", line 15, in route 
Jan 19 07:13:22 pulse-actions app/worker2.1:     treeherder_runnable.on_runnable_job_prod_event(data, message, dry_run) 
Jan 19 07:13:22 pulse-actions app/worker2.1:   File "/app/pulse_actions/handlers/treeherder_runnable.py", line 20, in on_runnable_job_prod_event 
Jan 19 07:13:22 pulse-actions app/worker2.1:     return on_runnable_job_event(data, message, dry_run, stage=False) 
Jan 19 07:13:22 pulse-actions app/worker2.1:   File "/app/pulse_actions/handlers/treeherder_runnable.py", line 65, in on_runnable_job_event 
Jan 19 07:13:22 pulse-actions app/worker2.1:     requester)

**Comment by armenzg** [comment]
I made a deployment.
It might work again.
Please let me know.

**Comment by armenzg** [comment]
I have not seen this happen again.
