### ISSUE TITLE
Handle SIGTERM signals from Heroku in a better way

### ISSUE THREAD

**Issue by armenzg** [mozilla/pulse_actions#48]
When making a deployment, it can sometimes trigger a lot of IOError: Socket closed exceptions (over 20 of them).

```
 Jan 20 11:41:15 pulse-actions heroku/worker2.1: State changed from up to starting 
Jan 20 11:41:18 pulse-actions heroku/worker2.1: Starting process with command `python pulse_actions/worker.py --topic-base resultset_actions,manual_backfill,runnable` 
Jan 20 11:41:19 pulse-actions heroku/worker2.1: Stopping all processes with SIGTERM 
Jan 20 11:41:19 pulse-actions heroku/worker2.1: State changed from starting to up 
Jan 20 11:41:20 pulse-actions heroku/worker2.1: Process exited with status 143 
Jan 20 11:41:21 pulse-actions app/worker2.1: root	 INFO:	 Console output logs INFO level messages. 
Jan 20 11:41:21 pulse-actions app/worker2.1: root	 INFO:	 Listening on [u'exchange/treeherder/v1/resultset-actions', u'exchange/treeherder/v1/job-actions', u'exchange/treeherder/v1/resultset-runnable-job-actions'], with topic [u'#.#', u'buildbot.#.backfill', u'#'] 
Jan 20 11:41:24 pulse-actions app/worker2.1: Traceback (most recent call last): 
Jan 20 11:41:24 pulse-actions app/worker2.1:   File "pulse_actions/worker.py", line 75, in run_pulse 
Jan 20 11:41:24 pulse-actions app/worker2.1:     pulse.listen() 
Jan 20 11:41:24 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/mozillapulse/consumers.py", line 148, in listen 
Jan 20 11:41:24 pulse-actions app/worker2.1:     on_connect_callback=on_connect_callback 
Jan 20 11:41:24 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/mozillapulse/consumers.py", line 166, in _build_consumer 
Jan 20 11:41:24 pulse-actions app/worker2.1:     exchange(self.connection).declare(passive=True) 
Jan 20 11:41:24 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/kombu/abstract.py", line 69, in __call__ 
Jan 20 11:41:24 pulse-actions app/worker2.1:     return self.bind(channel) 
Jan 20 11:41:24 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/kombu/abstract.py", line 73, in bind 
Jan 20 11:41:24 pulse-actions app/worker2.1:     return copy(self).maybe_bind(channel) 
Jan 20 11:41:24 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/kombu/abstract.py", line 78, in maybe_bind 
Jan 20 11:41:24 pulse-actions app/worker2.1:     self._channel = maybe_channel(channel) 
Jan 20 11:41:24 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/kombu/connection.py", line 1054, in maybe_channel 
Jan 20 11:41:24 pulse-actions app/worker2.1:     return channel.default_channel 
Jan 20 11:41:24 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/kombu/connection.py", line 756, in default_channel 
Jan 20 11:41:24 pulse-actions app/worker2.1:     self.connection 
Jan 20 11:41:24 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/kombu/connection.py", line 741, in connection 
Jan 20 11:41:24 pulse-actions app/worker2.1:     self._connection = self._establish_connection() 
Jan 20 11:41:24 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/kombu/connection.py", line 696, in _establish_connection 
Jan 20 11:41:24 pulse-actions app/worker2.1:     conn = self.transport.establish_connection() 
Jan 20 11:41:24 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 116, in establish_connection 
Jan 20 11:41:24 pulse-actions app/worker2.1:     conn = self.Connection(**opts) 
Jan 20 11:41:24 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/amqp/connection.py", line 180, in __init__ 
Jan 20 11:41:24 pulse-actions app/worker2.1:     (10, 30),  # tune 
Jan 20 11:41:24 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/amqp/abstract_channel.py", line 67, in wait 
Jan 20 11:41:24 pulse-actions app/worker2.1:     self.channel_id, allowed_methods, timeout) 
Jan 20 11:41:24 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/amqp/connection.py", line 241, in _wait_method 
Jan 20 11:41:24 pulse-actions app/worker2.1:     channel, method_sig, args, content = read_timeout(timeout) 
Jan 20 11:41:24 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/amqp/connection.py", line 330, in read_timeout 
Jan 20 11:41:24 pulse-actions app/worker2.1:     return self.method_reader.read_method() 
Jan 20 11:41:24 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/amqp/method_framing.py", line 189, in read_method 
Jan 20 11:41:24 pulse-actions app/worker2.1:     raise m 
Jan 20 11:41:24 pulse-actions app/worker2.1: IOError: Socket closed 
```

**Comment by armenzg** [comment]
I guess the python script should learn how to handle SIGTERM signals and close the pulse listerners.

**Comment by armenzg** [comment]
Not important enough and hard to test.
