### ISSUE TITLE
Handle invalid builders

### ISSUE THREAD

**Issue by armenzg** [mozilla/pulse_actions#52]
In https://bugzilla.mozilla.org/show_bug.cgi?id=1242038 I noticed that we have old builder names being sent over the pulse wire from Treeherder.
This is probably because the job was originally represented as Rev5 instead of Rev7.
For now, I will substitute Rev5 requests for Rev7 and see if valid use that.

Jan 22 12:18:29 pulse-actions app/worker2.1: th_buildbot	 INFO:	 backfill action requested by wkocher@mozilla.com on repo_name mozilla-inbound with job_id: 20313404 
Jan 22 12:18:31 pulse-actions app/worker2.1: mozci	 INFO:	 We want to find a job for 'Rev5 MacOSX Yosemite 10.10 mozilla-inbound opt test reftest' in this range: [a61bb2a7ffa3:114a806647a2] (7 revisions) 
Jan 22 12:18:34 pulse-actions app/worker2.1: mozci	 INFO:	 We want to have 1 job(s) of Rev5 MacOSX Yosemite 10.10 mozilla-inbound opt test reftest on these revisions:  
Jan 22 12:18:34 pulse-actions app/worker2.1: mozci	 INFO:	 We found a job for buildername 'Rev5 MacOSX Yosemite 10.10 mozilla-inbound opt test reftest' on b7ea61be4cad91d1e3d69e22d1c1e0a1b4bb1501 
Jan 22 12:18:34 pulse-actions app/worker2.1: mozci	 INFO:	 a61bb2a7ffa3667eba17dbe8826faf956656dd8b 
Jan 22 12:18:34 pulse-actions app/worker2.1: mozci	 INFO:	  
Jan 22 12:18:34 pulse-actions app/worker2.1: mozci	 INFO:	 === a61bb2a7ffa3667eba17dbe8826faf956656dd8b === 
Jan 22 12:18:34 pulse-actions app/worker2.1: mozci	 INFO:	 We want to have 1 job(s) of Rev5 MacOSX Yosemite 10.10 mozilla-inbound opt test reftest 
Jan 22 12:18:36 pulse-actions app/worker2.1: mozci	 INFO:	 We have found 0 potential job(s) matching 'Rev5 MacOSX Yosemite 10.10 mozilla-inbound opt test reftest' on a61bb2a7ffa3667eba17dbe8826faf956656dd8b. We need to trigger more. 
Jan 22 12:18:36 pulse-actions app/worker2.1: mozci	 INFO:	 ===> We want to trigger 'Rev5 MacOSX Yosemite 10.10 mozilla-inbound opt test reftest' on revision 'a61bb2a7ffa3667eba17dbe8826faf956656dd8b' a total of 1 time(s). 
Jan 22 12:18:36 pulse-actions app/worker2.1: mozci	 INFO:	  
Jan 22 12:18:36 pulse-actions app/worker2.1: mozci	 ERROR:	 We didn't find a build job matching Rev5 MacOSX Yosemite 10.10 mozilla-inbound opt test reftest 
Jan 22 12:18:36 pulse-actions app/worker2.1: Traceback (most recent call last): 
Jan 22 12:18:36 pulse-actions app/worker2.1:   File "pulse_actions/worker.py", line 75, in run_pulse 
Jan 22 12:18:36 pulse-actions app/worker2.1:     pulse.listen() 
Jan 22 12:18:36 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/mozillapulse/consumers.py", line 151, in listen 
Jan 22 12:18:36 pulse-actions app/worker2.1:     self._drain_events_loop() 
Jan 22 12:18:36 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/mozillapulse/consumers.py", line 198, in _drain_events_loop 
Jan 22 12:18:36 pulse-actions app/worker2.1:     self.connection.drain_events(timeout=self.timeout) 
Jan 22 12:18:36 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/kombu/connection.py", line 275, in drain_events 
Jan 22 12:18:36 pulse-actions app/worker2.1:     return self.transport.drain_events(self.connection, **kwargs) 
Jan 22 12:18:36 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 95, in drain_events 
Jan 22 12:18:36 pulse-actions app/worker2.1:     return connection.drain_events(**kwargs) 
Jan 22 12:18:36 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/amqp/connection.py", line 326, in drain_events 
Jan 22 12:18:36 pulse-actions app/worker2.1:     return amqp_method(channel, args, content) 
Jan 22 12:18:36 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/amqp/channel.py", line 1909, in _basic_deliver 
Jan 22 12:18:36 pulse-actions app/worker2.1:     fun(msg) 
Jan 22 12:18:36 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/kombu/messaging.py", line 598, in _receive_callback 
Jan 22 12:18:36 pulse-actions app/worker2.1:     return on_m(message) if on_m else self.receive(decoded, message) 
Jan 22 12:18:36 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/kombu/messaging.py", line 564, in receive 
Jan 22 12:18:36 pulse-actions app/worker2.1:     [callback(body, message) for callback in callbacks] 
Jan 22 12:18:36 pulse-actions app/worker2.1:   File "pulse_actions/worker.py", line 66, in handler_with_dry_run 
Jan 22 12:18:36 pulse-actions app/worker2.1:     return event_handler(data, message, dry_run) 
Jan 22 12:18:36 pulse-actions app/worker2.1:   File "/app/pulse_actions/handlers/route_functions.py", line 13, in route 
Jan 22 12:18:36 pulse-actions app/worker2.1:     treeherder_buildbot.on_buildbot_event(data, message, dry_run) 
Jan 22 12:18:36 pulse-actions app/worker2.1:   File "/app/pulse_actions/handlers/treeherder_buildbot.py", line 74, in on_buildbot_event 
Jan 22 12:18:36 pulse-actions app/worker2.1:     dry_run=dry_run 
Jan 22 12:18:36 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/mozci/mozci.py", line 582, in manual_backfill 
Jan 22 12:18:36 pulse-actions app/worker2.1:     'builders': [buildername]} 
Jan 22 12:18:36 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/mozci/mozci.py", line 502, in trigger_range 
Jan 22 12:18:36 pulse-actions app/worker2.1:     trigger_build_if_missing=trigger_build_if_missing) 
Jan 22 12:18:36 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/mozci/mozci.py", line 389, in trigger_job 
Jan 22 12:18:36 pulse-actions app/worker2.1:     will_use_buildapi=True 
Jan 22 12:18:36 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/mozci/mozci.py", line 129, in determine_trigger_objective 
Jan 22 12:18:36 pulse-actions app/worker2.1:     build_buildername = determine_upstream_builder(buildername) 
Jan 22 12:18:36 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/mozci/platforms.py", line 185, in determine_upstream_builder 
Jan 22 12:18:36 pulse-actions app/worker2.1:     raise MozciError("No build job matching %s found." % buildername) 
Jan 22 12:18:36 pulse-actions app/worker2.1: MozciError: No build job matching Rev5 MacOSX Yosemite 10.10 mozilla-inbound opt test reftest found.

**Comment by armenzg** [comment]
Once this lands, we should error out on invalid builders.
I should make these substitutions across the board.

**Comment by armenzg** [comment]
Associated bug https://bugzilla.mozilla.org/show_bug.cgi?id=1242725.

The first pass added this functionality to pulse_actions and we should not have the issue anymore.
However, after writing it, I believe it should live under mozci.
I will follow up on bug 1242725 to do this.

For now this has been fixed:
https://github.com/mozilla/pulse_actions/commit/22aa3fafce832c3cbd42243c1970e56e999a37aa
